#application.properties
spring.application.name=cinebook

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:h2:~/cinebook
#spring.datasource.url=jdbc:h2:mem:cineboo
spring.datasource.url=${postgresql://cinebook_user:6Kq59rK8JAYlS5tl7suKSLdiKyFOTV34@dpg-d8ft2e77f7vs73enlohg-a/cinebook_eop7}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# API
cinebook.kakao.api-key=3d4bd63464591703c4011d6f3cd332b0
cinebook.movie.api-key=V124986WMPC2V942606N
